services:
  - type: web
    name: cursalo
    env: node
    buildCommand: |
      # Install frontend dependencies and build
      npm install
      npm run build
      # Install server dependencies
      cd server
      npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production