services:
  - type: web
    name: cursalo
    env: node
    rootDir: .
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production